let _ = require('lodash');

let people = [{
    "id": 1,
    "first_name": "Elfrida",
    "last_name": "Barthelmes",
    "email": "ebarthelmes0@marriott.com",
    "gender": "Female",
    "ip_address": "233.195.64.226"
  }, {
    "id": 2,
    "first_name": "Esmeralda",
    "last_name": "Kew",
    "email": "ekew1@51.la",
    "gender": "Female",
    "ip_address": "7.45.136.83"
  }, {
    "id": 3,
    "first_name": "Artemis",
    "last_name": "Ovey",
    "email": "aovey2@cloudflare.com",
    "gender": "Male",
    "ip_address": "66.194.93.41"
  }, {
    "id": 4,
    "first_name": "Aridatha",
    "last_name": "Dunbobbin",
    "email": "adunbobbin3@i2i.jp",
    "gender": "Female",
    "ip_address": "110.101.184.93"
  }, {
    "id": 5,
    "first_name": "Boris",
    "last_name": "Saby",
    "email": "bsaby4@spiegel.de",
    "gender": "Male",
    "ip_address": "164.11.185.194"
  }, {
    "id": 6,
    "first_name": "Aliza",
    "last_name": "Willey",
    "email": "awilley5@scribd.com",
    "gender": "Female",
    "ip_address": "121.250.127.244"
  }, {
    "id": 7,
    "first_name": "Bob",
    "last_name": "Fillgate",
    "email": "bfillgate6@mit.edu",
    "gender": "Male",
    "ip_address": "115.190.21.224"
  }, {
    "id": 8,
    "first_name": "D'arcy",
    "last_name": "Blankley",
    "email": "dblankley7@about.me",
    "gender": "Male",
    "ip_address": "216.145.135.177"
  }, {
    "id": 9,
    "first_name": "Nestor",
    "last_name": "McRavey",
    "email": "nmcravey8@goo.gl",
    "gender": "Male",
    "ip_address": "123.30.229.219"
  }, {
    "id": 10,
    "first_name": "Louella",
    "last_name": "Baggett",
    "email": "lbaggett9@blinklist.com",
    "gender": "Female",
    "ip_address": "150.131.180.204"
  }, {
    "id": 11,
    "first_name": "Hunfredo",
    "last_name": "Sponton",
    "email": "hspontona@earthlink.net",
    "gender": "Male",
    "ip_address": "253.2.219.36"
  }, {
    "id": 12,
    "first_name": "Jephthah",
    "last_name": "Atte-Stone",
    "email": "jattestoneb@mozilla.org",
    "gender": "Male",
    "ip_address": "5.14.33.90"
  }, {
    "id": 13,
    "first_name": "Matelda",
    "last_name": "Matley",
    "email": "mmatleyc@ft.com",
    "gender": "Female",
    "ip_address": "30.115.55.207"
  }, {
    "id": 14,
    "first_name": "Hillel",
    "last_name": "Metherell",
    "email": "hmetherelld@gnu.org",
    "gender": "Male",
    "ip_address": "100.75.51.226"
  }, {
    "id": 15,
    "first_name": "Hamlin",
    "last_name": "Zanicchelli",
    "email": "hzanicchellie@economist.com",
    "gender": "Male",
    "ip_address": "10.14.91.165"
  }, {
    "id": 16,
    "first_name": "Shelden",
    "last_name": "Andriesse",
    "email": "sandriessef@bizjournals.com",
    "gender": "Male",
    "ip_address": "79.40.1.19"
  }, {
    "id": 17,
    "first_name": "Julianna",
    "last_name": "Suddards",
    "email": "jsuddardsg@sitemeter.com",
    "gender": "Female",
    "ip_address": "173.105.87.17"
  }, {
    "id": 18,
    "first_name": "Pinchas",
    "last_name": "Dohmer",
    "email": "pdohmerh@mayoclinic.com",
    "gender": "Male",
    "ip_address": "214.227.226.208"
  }, {
    "id": 19,
    "first_name": "Rozele",
    "last_name": "Olsen",
    "email": "rolseni@thetimes.co.uk",
    "gender": "Female",
    "ip_address": "79.15.35.48"
  }, {
    "id": 20,
    "first_name": "Bradney",
    "last_name": "Bonellie",
    "email": "bbonelliej@java.com",
    "gender": "Male",
    "ip_address": "246.192.90.76"
  }];

  let femaleCount = _.filter(people, {gender: "Female"}).length;

console.log(femaleCount + " females!");
console.log('module2 stuff');